###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
    application:
      name: app-cy-member
    redis:
      #host: 47.106.239.93
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          max-idle: 100
          min-idle: 1
          max-active: 1000
          max-wait: -1
###数据库相关连接
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      #url: jdbc:mysql://47.106.239.93:3308/cy_member?useUnicode=true&characterEncoding=UTF-8
      url: jdbc:mysql://127.0.0.1:3306/cy_member?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka #http://192.168.222.129:8080/eureka
####swagger相关配置
swagger:
  base-package: com.cy.member.service
  title: SpringCloud2.x构建微服务电商项目-会员服务接口
  description: 该项目“基于SpringCloud2.x构建微服务电商项目”
  version: 1.1
  terms-of-service-url: www.cy.com
  contact:
    name: 陈勇
    email: 986275730@qq.com
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.cy.member.mapper: DEBUG

